version: '3'
services:
  database:
    image: postgres:15
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: password
      POSTGRES_DB: directus

  directus:
    image: directus/directus:latest
    ports:
      - "8055:8055"
    volumes:
      - ./data/uploads:/directus/uploads
      - ./data/extensions:/directus/extensions
    depends_on:
      - database
    environment:
      KEY: "una-chiave-segreta-molto-lunga"
      SECRET: "un-segreto-molto-lungo"
      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "password"
      # Permette di connettersi dal frontend locale
      CORS_ENABLED: "true"
      CORS_ORIGIN: "http://localhost:5173"
      CORS_CREDENTIALS: "true"
      AUTH_DISABLE_DEFAULT_ADMIN_ROLE_CHECK: "true"